services:
  web:
    domain: ${HOST}
    image: drupal:10-apache
    port: 80
    ports:
      - 8080
    resources:
      - db1
    volumeOptions:
      - awsEfs:
          id: "drupal"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/modules"
      - awsEfs:
          id: "drupal"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/profiles"
      - awsEfs:
          id: "drupal"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/themes"
      - awsEfs:
          id: "drupal"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/sites"
resources:
  db1:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16


