environment:
  - NODE_ENV=production
  - PORT=3000
params:
  aws-logs:
    cw-retention: 30
services:
  web:
    build: .
    command: node app.js
    port: 3000
    scale:
      count: 1
      cpu: 128
      memory: 256
    resources:
      - db
resources:
  db:
    type: postgres
    options:
      version: 13
