services:
  web:
    domain: ${HOST}
    image: drupal:10-apache
    port: 80
    ports:
      - 8080
    resources:
      - db1
    volumeOptions:
      - awsEfs:
          id: "modules"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/modules"
      - awsEfs:
          id: "profiles"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/profiles"
      - awsEfs:
          id: "themes"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/themes"
      - awsEfs:
          id: "sites"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/sites"

balancers:
  custom:
    service: web
    ports:
      3000: 8080
      5000: 80
resources:
  db1:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16


