services:
  web:
    domain: ${HOST}
    image: drupal:10.2.8
    port: 80
    health:
      disable: true
    resources:
      - db1
    initContainer:
      image: drupal:10.2.8
      command: "bash -c 'cp -r /var/www/html/sites/default/ /data/ && chmod 777 -R /data/'"
      volumeOptions:
        - awsEfs:
            id: "4"
            accessMode: ReadWriteMany
            mountPath: "/data/"
    volumeOptions:
      - awsEfs:
          id: "1"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/modules"
      - awsEfs:
          id: "2"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/profiles"
      - awsEfs:
          id: "3"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/themes"
      - awsEfs:
          id: "4"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/sites"
resources:
  db1:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16
