services:
  web:
    domain: ${HOST}
    build: .
    command: node app.js
    port: 3001
    environment:
      - PORT=3001
    resources:
      - db
resources:
  db:
    type: postgres
    options:
      version: 13
