services:
  web:
    build: .
    port: 80
    ports:
     - 8080
    resources:
      - db1
resources:
  db1:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16


