services:
  web:
    domain: ${HOST}
    image: drupal:10-apache
    port: 80
    ports:
      - 8080
    lifecycle:
      postStart: "/bin/sh -c 'cp -r /var/www/html/sites//data/; chown www-data:www-data/data/-R'"
    resources:
      - db2
    volumeOptions:
      - awsEfs:
          id: "drupal1"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/modules"
      - awsEfs:
          id: "drupal1"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/profiles"
      - awsEfs:
          id: "drupal1"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/themes"
      - awsEfs:
          id: "drupal1"
          accessMode: ReadWriteMany
          mountPath: "/var/www/html/sites"
resources:
  db2:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16


