services:
  web:
    domain: ${HOST}
    build: .
    port: 80
    ports:
      - 8080
    resources:
      - db1
balancers:
  custom:
    service: web
    ports:
      3000: 8080
      5000: 80
resources:
  db1:
    type: postgres
    options:
      storage: 10
      class: db.t3.large
      version: 16


