services:
  web:
    domain: ${HOST}
    build: .
    command: node app.js
    port: 3001
    environment:
      - PORT=3001
    resources:
      - my-sql1
resources:
  my-sql1:
    type: mysql
    options:
      version: "8.0"
      class: "db.t3.small"
      storage: 5
      encrypted: true
      durable: true
